version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - 你的社工库目录:/data:ro
    ports:
      - "5000:5000"
    environment:
      - GUNICORN_CMD_ARGS=-w 1 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker
      #- FLASK_ENV=development
      #- PYTHONUNBUFFERED=TRUE
    restart: always
