name: Manual Docker Build & Push

# 仅保留手动触发（workflow_dispatch）
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker 镜像标签（如：v1.0.0、test）'
        required: true
        default: 'test'  # 默认标签（可修改）

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码到 GitHub 服务器
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 初始化 Docker Buildx（支持多架构构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. 登录 Docker Hub（使用 GitHub Secrets 安全存储凭证）
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub 用户名（需在 GitHub Secrets 中配置）
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # Docker Hub 访问令牌（需在 GitHub Secrets 中配置）

      # 4. 构建并推送 Docker 镜像（标签为手动输入的 image_tag）
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .                         
          file: ./Dockerfile                  
          push: true                       
          tags: |                           
            haoqi7/sed:${{ inputs.image_tag }} 
            haoqi7/sed:latest                  
