name: Docker Build & Push

# 触发条件：支持手动触发（workflow_dispatch）和推送到 main 分支（可选保留）
on:
  push:
    branches: [ "main" ]  # 保留原有自动触发（可选，可删除）
  workflow_dispatch:      # 新增手动触发
    inputs:
      image_tag:
        description: 'Docker Image Tag (e.g., test, v1.0.0)'  # 输入框描述
        required: true                                        # 必填
        default: 'test'                                       # 默认值

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub 用户名（Secrets）
          password: ${{ secrets.DOCKERHUB_TOKEN }}     # Docker Hub 访问令牌（Secrets）

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # 你的 Dockerfile 路径（根据项目实际路径调整）
          push: true
          tags: |
            haoqi7/sed:latest                   # 保留 latest 标签（可选）
            haoqi7/sed:${{ github.sha }}        # 提交 SHA 标签（可选）
